name: Deploy Substrate Node on AWS

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version to deploy (e.g., v1.0.0)"
        required: true

jobs:
  deploy-node:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install AWS CLI
      run: |
        sudo apt update
        sudo apt install -y awscli

    - name: Create AWS EC2 instance for the node
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        INSTANCE_ID=$(aws ec2 run-instances --image-id ami-12345678 --count 1 --instance-type t3.medium \
          --key-name my-key --security-groups my-security-group \
          --user-data file://setup_node.sh \
          --query "Instances[0].InstanceId" --output text)
        
        echo "NODE_INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
        echo "New AWS EC2 instance created with ID: $INSTANCE_ID"

    - name: Get Public IP of the Instance
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $NODE_INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
        echo "NODE_PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
        echo "AWS Instance Public IP: $PUBLIC_IP"

    - name: Wait for Instance to Be Ready
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        echo "Waiting for AWS instance to be ready..."
        aws ec2 wait instance-status-ok --instance-ids $NODE_INSTANCE_ID
        echo "AWS instance is now running."

    - name: Log in to AWS Instance & Deploy Node
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        echo "Logging into AWS Instance..."
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/my-key.pem ubuntu@$NODE_PUBLIC_IP <<EOF
          echo "Downloading latest Substrate node binary..."
          wget -O main-node https://github.com/${{ github.repository }}/releases/download/${{ inputs.release_version }}/main-node
          chmod +x main-node
          sudo mv main-node /usr/local/bin/substrate-node
          
          echo "Starting Substrate node..."
          sudo systemctl restart substrate-node
        EOF
